Update buildspec.yml

diff --git a/codepipeline/buildspec.yml b/codepipeline/buildspec.yml
--- a/codepipeline/buildspec.yml
+++ b/codepipeline/buildspec.yml
@@ -31,16 +31,56 @@ phases:
       - echo "Post Build start at $(date)"
       - echo "${CODEDEPLOY_APPSPEC}" > appspec.yml
       - echo "${MAGENTO_ENV}" > app/etc/env.php
-      - echo "rm -rf --one-file-system --preserve-root" > cleanup.sh
       - |
-        echo "if [ "\${DEPLOYMENT_GROUP_ID}" == "\${ADMIN_DEPLOYMENT_GROUP_ID}" ]; then
+        echo "
+        #!/bin/bash
+        # before install
+        BUNDLE_DIR="/opt/codedeploy-agent/deployment-root/${DEPLOYMENT_GROUP_ID}/${DEPLOYMENT_ID}/deployment-archive"
+        APPSPEC_FILE="${BUNDLE_DIR}/appspec.yml"
+        # Replace paths in appspec.yml
+        sed -i "s|deployment_id|\${DEPLOYMENT_ID}|g" "${APPSPEC_FILE}"
+        # Symlink shared folders
+        SHARED="/home/${BRAND}/shared"
+        NEW_RELEASE="/home/${BRAND}/releases/\${DEPLOYMENT_ID}"
+        ln -nfs "\${SHARED}/var" "\${NEW_RELEASE}/var"
+        ln -nfs "\${SHARED}/pub/media" "\${NEW_RELEASE}/pub/media"
+        " > setup.sh
+      - |
+        echo "
+        #!/bin/bash
+        # after install
+        NEW_RELEASE="/home/${BRAND}/releases/\${DEPLOYMENT_ID}"
+        PUBLIC_HTML="/home/${BRAND}/public_html"
+        # Ensure the new release directory exists
+        if [ ! -d "\${NEW_RELEASE}" ]; then
+          echo "New release directory not found!"
+          echo "Deployment error!"
+         exit 1
+        fi
+        # Perform symlink swap to point to the new release
+        ln -nfs "\${NEW_RELEASE}" "\${PUBLIC_HTML}"
+        " > deploy.sh
+      - |
+        echo "
+        #!/bin/bash
+        # application start
+        if [ "\${DEPLOYMENT_GROUP_ID}" == "\${ADMIN_DEPLOYMENT_GROUP_ID}" ]; then
         bin/magento setup:db:status --no-ansi -n
         if [[ \$? -ne 0 ]]; then
         bin/magento setup:upgrade --keep-generated --no-ansi -n
         fi
         sudo cacheflush
-        fi" > setup.sh
-      - chmod +x cleanup.sh setup.sh
+        fi
+        " > upgrade.sh
+      - |
+        echo "
+        #!/bin/bash
+        # validate service
+        cd /home/${BRAND}/releases
+        ls -dt */ | tail -n +2 | xargs rm -rf
+        rm setup.sh deploy.sh upgrade.sh cleanup.sh appspec.yml
+        " > cleanup.sh
+      - chmod +x setup.sh deploy.sh upgrade.sh cleanup.sh
       - echo "Post Build end at $(date)"
 artifacts:
     files:
